.TH "sltool" "5" "Mar 2016" "1.4.0" "sltool man page"

.SH NAME
sltool

.SH SYNOPSIS
sl [-b] [--buses] [-m] [--metros] [-h] [--help] <search>

.SH DESCRIPTION
sltool is a lightweight CLI for getting estimated time of arrival on Stockholms subways and buses. It makes use of SL's API's for searching of sites and getting realtime information on a site. 
If you find any bugs or have ideas about improvements, it would help me a great deal if you made an issue about it in the github repository @ https://github.com/solrankos/sltool.

.SH OPTIONS
.IP -h, --help
display help

.SH EXAMPLES
To search for a station type "sl <searchstring>".
You will the be prompted with five options. Pelase select one of them to get ETA on that station.
There is a possibillty that the option you selected doesn't contain any arrivals.

.SH BUGS/IMPROVEMENTS
If you find any bugs or have ideas about improvements, it would help me a great deal if you made an issue about it in the github repository @ https://github.com/solrankos/sltool.

.SH AUTHOR
Oscar Karlsson
